/*
 * @(#)BlogContentPane.java created Jul 26, 2005 Casalino
 *
 * Copyright (c) 1996-2004 Luca Lutterotti All Rights Reserved.
 *
 * This software is the research result of Luca Lutterotti and it is 
 * provided as it is as confidential and proprietary information.  
 * You shall not disclose such Confidential Information and shall use 
 * it only in accordance with the terms of the license agreement you 
 * entered into with the author.
 *
 * THE AUTHOR MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF THE
 * SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 * PURPOSE, OR NON-INFRINGEMENT. THE AUTHOR SHALL NOT BE LIABLE FOR ANY DAMAGES
 * SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
 * THIS SOFTWARE OR ITS DERIVATIVES.
 *
 */

package it.unitn.ing.rista.awt;

import com.sun.syndication.feed.synd.*;

import javax.swing.*;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import javax.swing.text.html.*;
import java.awt.*;
import java.net.URL;

import it.unitn.ing.rista.util.*;


/**
 * The BlogContentPane is a class
 * <p/>
 * Description
 *
 * @author Luca Lutterotti
 * @version $Revision: 1.2 $, $Date: 2006/01/19 14:45:52 $
 * @since JDK1.1
 */

public class BlogContentPane extends JEditorPane {

  private HTMLEditorKit _editorKit = new HTMLEditorKit();

  public BlogContentPane() {
    super();
    try {
      jbInit();
      postInit();
    } catch(Exception e) {
      e.printStackTrace();
    }

  }

  private void jbInit() throws Exception {
    StyleSheet articleCSS = new StyleSheet();
    articleCSS.importStyleSheet(new URL(MaudPreferences.getPref("MaudRSSfeed.css_location",
        "http://stargo.ing.unitn.it/home/feed/Articles.css")));
    _editorKit.setStyleSheet(articleCSS);
    setEditorKit( _editorKit );
    setEditable( false );
  }


  private void postInit() throws Exception
  {
    this.addHyperlinkListener( new HyperlinkListener()
    {
      public void hyperlinkUpdate( HyperlinkEvent e )
      {
        if ( e.getEventType() == HyperlinkEvent.EventType.ACTIVATED )
        {
          Misc.openBrowserOnURL( e.getURL() );
        }
      }
    });
  }

  /**
   * Sets the text in the text component for the {@link SyndFeed} given.
   *
   * @param blogList The {@link java.util.List} containing the feeds to display
   */
  public void setBlogText(java.util.List blogList) {
/*    StyleSheet styles = _editorKit.getStyleSheet();

    Enumeration rules = styles.getStyleNames();
    while (rules.hasMoreElements()) {
        String name = (String) rules.nextElement();
        Style rule = styles.getStyle(name);
        System.out.println(rule.toXRDcatString());
    }*/
    if (blogList == null)
      return;
    int numberOfEntries = blogList.size();

    StringBuffer text = new StringBuffer( 512 );

/*      text.append("<!doctype HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">");
      text.append("<html>");
      text.append("<head>");
      text.append("<title>");
      text.append("Maud RSS feed");
      text.append("</title>");
      text.append("<!-- Generated by ");
      text.append("Maud RSS at ");
      text.append((new Date()).toXRDcatString());
      text.append("for MaudRSSFeed");
//      text.append(item.getUri().toXRDcatString());
      text.append("-->");
      text.append("<meta http-equiv=\"Content-Type\" content=\"text/html\" charset=\"UTF-8\" />");
      text.append("<meta id=\"MaudSyndicationInfo\">");
      text.append("<style type=\"text/css\">");
      text.append("@import url(http://127.0.0.1/home/feed/Articles.css);");
      text.append("</style>");
      text.append("<base href=\"\">");
      text.append("</head>");

      text.append("<body>");*/

      text.append("<div id=\"scroller\">");
//      text.append("<div id=\"noarticles\">");
//      text.append("No Articles");
//      text.append("</div>");
      text.append("<div id=\"contentarea\">");
      text.append("<div class=content id=\"content\" style=\"appleLineClamp: 100%\">");
    for (int i = 0; i < numberOfEntries; i++) {
      SyndEntryImpl item = (SyndEntryImpl) blogList.get(i);
      if (item != null) {

        text.append("<div name=\"");
        text.append(Integer.toString(i));
        text.append("\" class=read>");

        text.append("<div class=articlefooter></div>");
        text.append("<a class=articlehead ");
        text.append("href=");
        text.append(item.getLink());
        text.append("\" target=\"_self\">");

        if (item.getTitle() != null) {
        text.append("<div class=subject title=\"");
        text.append(item.getTitle());
        text.append("\">");
        text.append(item.getTitle());
        text.append("</div>");
        }

        if (item.getAuthor() != null) {
        text.append("<div class=author title=\"");
        text.append(item.getAuthor());
        text.append("\">");
        text.append(item.getAuthor());
        text.append("</div>");
        }

        if (item.getPublishedDate() != null) {
        text.append("<div class=date title=\"");
        text.append(item.getPublishedDate());
        text.append("\">");
        text.append(item.getPublishedDate());
        text.append("</div>");
        }

        text.append("</a>");

        text.append("<div class=articlebody>");
        text.append(item.getDescription().getValue());

        if (item.getLink() != null) {
        text.append("<a class=articlelink href=\"");
        text.append(item.getLink());
        text.append("\" target=\"_self\">Read more...</a>");
        }
        text.append("</div>");

        text.append("</div>");

      }
    }
    text.append("</div>");
    text.append("</div>");
    text.append("</div>");

/*    text.append("</body>");
    text.append("</html>");

    System.out.println( text.toXRDcatString() );*/
    setText( text.toString() );
    setCaretPosition( 0 );

  }


  /** Test Main **/
  public static void FeedFrame(SyndFeed item) {
    JFrame f = new JFrame();
    BlogContentPane pane = new BlogContentPane();
    pane.setBlogText( item.getEntries() );
    f.getContentPane().setLayout( new BorderLayout() );
    f.getContentPane().add( new JScrollPane( pane ), BorderLayout.CENTER );
    f.setSize( 700, 500 );
    f.setDefaultCloseOperation( JFrame.DISPOSE_ON_CLOSE );
    f.setVisible(true);
  }

}

/*
<!doctype HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <!-- Generated by Safari RSS at 2005-07-27 06:16:36 +0200 for file:///Users/luca/Sites/prova/RSSex.xml -->
    <meta http-equiv="Content-Type" content="text/html; charset="UTF-8" />
    <meta id="AppleSyndicationInfo">
    <link rel="icon" href="feed:///__rsrc__/favicon.tif" type="image/x-icon" />
                     <link rel="shortcut icon" href="feed:///__rsrc__/favicon.tif" type="image/x-icon" />
    <style type="text/css">
        @import url(feed:///__rsrc__/Articles.css);
        @import url(feed:///__rsrc__/ArticlesL10N.css);


    </style>
    <script language=JavaScript>
        sMinFirstDate = "null";
        sMaxLastDate = "null";
    </script>
    <title>XML.com</title>
    <base href="">
</head>
<body onClick="articleClicked(null)" onLoad="setup(null)">
    <script language=JavaScript src="feed:///__rsrc__/Articles.js"></script>

    <div id="sidebarbackground"></div>
    <div id="banner">
        <div id="title">

            <span id="titleText">XML.com</span>

        </div>
        <div id="counts">
            <span id="unreadcountwrapper"><span id="unreadcount" text="New"></span>, </span>
            <span id="totalcount" text="Total">0</span>
        </div>
    </div>

    <div id="scroller" onScroll="slipDiffScroll(this)"  >
        <div id="sidebar">
            <div class="group" id="filtergroup">
                <div class="grouptitle">Search Articles:</div>
                <input type=search id=searchfield results=0 incremental onKeyPress="handleScrollKeys(event)" onSearch="setContentFilter(this.value, 'Add Bookmark&hellip;', 'Bookmark This Search')"
                       placeholder="" value="">
            </div>

            <div class="group" id="slidergroup">
                <div class="grouptitle">Article Length:</div>
                <div id="sliderdiv">
                    <img src="feed:///__rsrc__/Smaller.tif" width="16" height="16" onclick="scaleToMin()">
                    <input id="slider" type="range" min="0" value="100" max="100" onmousedown="startScale()" onmouseup="endScale()" oninput="scaleArticles(this.value)" />
                    <img src="feed:///__rsrc__/Bigger.tif" width="16" height="16" onclick="scaleToMax()">
                </div>
            </div>

            <div class="group" id="sorts">
                <div class="grouptitle">Sort By:</div>

                    <div class=current name="1"> <a href="javascript:sortArticlesBy(1)">Date</a></div>

                    <div  name="3"> <a href="javascript:sortArticlesBy(3)">Title</a></div>

                    <div  name="4"> <a href="javascript:sortArticlesBy(4)">Source</a></div>

                    <div  name="2"> <a href="javascript:sortArticlesBy(2)">New</a></div>

            </div>

            <div class="group" id="timespans">
                <div class="grouptitle">Recent Articles:</div>

                    <div class=current name="0"
                            firstDate="" lastDate="" noarticles="No Articles">
                        <a href="javascript:setDateFilter(0)">All</a>
                    </div>

                    <div  name="1"
                            firstDate="144108000" lastDate="" noarticles="No Articles Today">
                        <a href="javascript:setDateFilter(1)">Today</a>
                    </div>

                    <div  name="2"
                            firstDate="144021600" lastDate="144108000" noarticles="No Articles Yesterday">
                        <a href="javascript:setDateFilter(2)">Yesterday</a>
                    </div>

                    <div  name="3"
                            firstDate="143589600" lastDate="" noarticles="No Articles in the Last Seven Days">
                        <a href="javascript:setDateFilter(3)">Last Seven Days</a>
                    </div>

                    <div  name="5"
                            firstDate="141861600" lastDate="" noarticles="No Articles This Month">
                        <a href="javascript:setDateFilter(5)">This Month</a>
                    </div>

                    <div  name="6"
                            firstDate="139269600" lastDate="141861600" noarticles="No Articles Last Month">
                        <a href="javascript:setDateFilter(6)">Last Month</a>
                    </div>

            </div>

            <div class="group" id="sourcelist">


                    <div class="grouptitle">Source:</div>
                    <div class="sourceLink"><a href=""><span id="sourceNameText">XML.com</span></a></div>

            </div>

            <div class="group">
                <div class="grouptitle">Actions:</div>
                <div id="mailto">
                    <a href="mail-link:">Mail Link to This Page</a>
                </div>
                <div id="bookmarkLink"  >
                    <a id="bookmarkHref" href="javascript:bookmarkFeed()" title="Bookmark this RSS page to automatically receive new articles.">Add Bookmark&hellip;</a>
                </div>
            </div>


                <div id="FOAFPlaceholder"></div>
                <script language="JavaScript">loadFOAF();</script>


        </div>

        <div id="noarticles">No Articles</div>

        <div id="contentarea">
            <div class="content" id="content" style="appleLineClamp: 100%;">
<!-- ARTICLES START HERE -->
<div name="0/1/3" class="read" onmousedown="return articleClicked(this)"
         articlesortdate="060649200" articlesorttitle="normalizing xml, par" articlesortsource="" sourceindex=""
          >

    <div class=articlefooter></div>
    <a class=articlehead href="http://www.xml.com/pub/a/2002/12/04/normalizing.html" target="_self" >

            <div class="subject" title="Normalizing XML, Part 2">Normalizing XML, Part 2</div>


            <div class="author" title="Will Provost">
                Will Provost
            </div>

        <div class="date" title="Dec 4, '02, 12:00 AM">
                Dec 4, '02, 12:00 AM
        </div>
    </a>

    <div class=articlebody>
        In this second and final look at applying relational normalization techniques to W3C XML Schema data modeling, Will Provost discusses when not to normalize, the scope of uniqueness and the fourth and fifth normal forms.

        <a class="articlelink" href="http://www.xml.com/pub/a/2002/12/04/normalizing.html" target="_self">Read more&hellip;</a>

    </div>
</div><div name="0/1/2" class="read" onmousedown="return articleClicked(this)"
         articlesortdate="060649200" articlesorttitle="the .net schema obje" articlesortsource="" sourceindex=""
          >

    <div class=articlefooter></div>
    <a class=articlehead href="http://www.xml.com/pub/a/2002/12/04/som.html" target="_self" >

            <div class="subject" title="The .NET Schema Object Model">The .NET Schema Object Model</div>


            <div class="author" title="Priya Lakshminarayanan">
                Priya Lakshminarayanan
            </div>

        <div class="date" title="Dec 4, '02, 12:00 AM">
                Dec 4, '02, 12:00 AM
        </div>
    </a>

    <div class=articlebody>
        Priya Lakshminarayanan describes in detail the use of the .NET Schema Object Model for programmatic manipulation of W3C XML Schemas.

        <a class="articlelink" href="http://www.xml.com/pub/a/2002/12/04/som.html" target="_self">Read more&hellip;</a>

    </div>
</div><div name="0/1/1" class="read" onmousedown="return articleClicked(this)"
         articlesortdate="060649200" articlesorttitle="svg's past and promi" articlesortsource="" sourceindex=""
          >

    <div class=articlefooter></div>
    <a class=articlehead href="http://www.xml.com/pub/a/2002/12/04/svg.html" target="_self" >

            <div class="subject" title="SVG's Past and Promising Future">SVG's Past and Promising Future</div>


            <div class="author" title="Antoine Quint">
                Antoine Quint
            </div>

        <div class="date" title="Dec 4, '02, 12:00 AM">
                Dec 4, '02, 12:00 AM
        </div>
    </a>

    <div class=articlebody>
        In this month&#39;s SVG column, Antoine Quint looks back at SVG&#39;s journey through 2002 and looks forward to 2003.

        <a class="articlelink" href="http://www.xml.com/pub/a/2002/12/04/svg.html" target="_self">Read more&hellip;</a>

    </div>
</div><span id="totalarticlecount" total="3" unread="0"></span>

<!-- END OF ARTICLES -->
        </div>
        <div id="pagination">
            <div class="pagination" align="center">
                <img id="previousarticle" src="feed:///__rsrc__/PreviousPage.tif" width="19" height="18" onclick="javascript:goToPage(-4)">
                <!-- Do not add space between the following spans -->
                <span id="previousarticles"><a href="javascript:goToPage(-3)">previous&hellip;</a></span><span id="currentarticles"><a href="javascript:goToPage(1)">1</a><a href="javascript:goToPage(2)">2</a><a href="javascript:goToPage(3)">3</a><a href="javascript:goToPage(4)">4</a><a href="javascript:goToPage(5)">5</a><a href="javascript:goToPage(6)">6</a><a href="javascript:goToPage(7)">7</a><a href="javascript:goToPage(8)">8</a><a href="javascript:goToPage(9)">9</a><a href="javascript:goToPage(10)">10</a></span><span id="nextarticles"><a href="javascript:goToPage(-2)">more&hellip;</a></span>
                <img id="nextarticle" src="feed:///__rsrc__/NextPage.tif" width="19" height="18" onclick="javascript:goToPage(-1)">
            </div>
        </div>
    </div>

<!-- END OF CONTENT AREA -->
    </div>

    <script language="JavaScript">

        updateSettingsIfAfter(1122437796305);
    </script>

</body>
</html>
<script language='JavaScript'>setupPagination(3, 0, 500);</script>
*/
